image: gitpod/workspace-full-vnc

ports:
  - port: 6080
    onOpen: open-preview

tasks:
  - name: Set VNC Resolution
    init: xrandr --fb 1280x800

  - init: npm install
    command: npm start

vscode:
  extensions:
    - ms-azuretools.vscode-docker
    - esbenp.prettier-vscode
    - dbaeumer.vscode-eslint
    - bradlc.vscode-tailwindcss
    - oderwat.indent-rainbow
    - Prisma.prisma
    - sleistner.vscode-fileutils
